# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'PizzaLizza' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PizzaLizza
  pod 'RxSwift'
  pod 'RxCocoa'

end
